- hosts: HP_A3600
  connection: local
  gather_facts: no
  tasks:
    - name: Enviar comandos ao Comware 5 via Paramiko shell
      comware5_command:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        commands:
          - system-view
          - vlan 115
          - name ansible115
          - quit
          - display vlan
      register: resultado

    - debug:
        var: resultado.output
