- hosts: HP_A3600
  connection: local
  gather_facts: no
  tasks:
    - name: Enviar comandos ao Comware 5 via Paramiko shell
      cogeti_cm.comware5.comware5_commands:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        commands:
          - system-view
          - vlan {{ vlan_id }}
          - name {{ vlan_nome }}
          - quit
          - display vlan
      register: resultado

    - debug:
        var: resultado.output
