- name: Gerenciar VLAN no grupo CISCO
  hosts: CISCO
  gather_facts: no
  connection: ansible.netcommon.network_cli
  tasks:
    - name: Configurar VLAN com ID e nome dinâmicos
      cisco.ios.ios_vlans:
        config:
          - vlan_id: "{{ vlan_id | int }}"
            name: "{{ vlan_name }}"
            state: active
            shutdown: disabled
