- name: Criar VLANs em switches Cisco e HP
  hosts: all
  gather_facts: no
  vars:
    vlans:
      - id: 10
        name: VLAN10
      - id: 20
        name: VLAN20

  tasks:

    - name: Configurar VLANs no switch Cisco
      when: "'cisco' in group_names"
      cisco.ios.ios_config:
        lines: "{{ vlan_lines }}"
      vars:
        ansible_network_os: cisco.ios.ios
        vlan_lines: >-
          {% for vlan in vlans %}
          vlan {{ vlan.id }}
          name {{ vlan.name }}
          {% endfor %}

    - name: Configurar VLANs no switch HP 3600
      when: "'hp_3600' in group_names"
      hpe.comware.comware_config:
        lines: "{{ vlan_lines }}"
      vars:
        ansible_network_os: hpe.comware.comware
        vlan_lines: >-
          {% for vlan in vlans %}
          vlan {{ vlan.id }}
          name {{ vlan.name }}
          {% endfor %}
