- hosts: HP_A3600
  connection: local
  gather_facts: no
  tasks:
    - name: Excluir VLAN via Comware 5
      cogeti_cm.comware5.comware5_commands:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        commands:
          - system-view
          - undo vlan {{ vlan_id }}
          - quit
          - display vlan
      register: resultado

    - name: Exibir resultado
      debug:
        var: resultado.output
