---
- name: Mostrar VLANs por porta nos switches
  hosts: all
  gather_facts: no

  tasks:

    - name: Obter VLANs e interfaces - Switch Cisco
      ansible.netcommon.cli_command:
        command: show vlan brief
      when: "'CISCO' in group_names"
      register: cisco_output
      failed_when: false

    - name: Processar e exibir VLANs - Cisco
      ansible.builtin.debug:
        msg: |
          {{ inventory_hostname }}:
          {% for line in cisco_output.stdout_lines if line | regex_search('^\\d+') %}
            {% set parts = line.split() %}
            {% set vlan = parts[0] %}
            {% set ports = line.split(None, 3)[-1].split(', ') if line.split(None, 3)|length > 3 else [] %}
            {% for port in ports %}
Porta: {{ port }} - VLAN: {{ vlan }}
            {% endfor %}
          {% endfor %}
      when: "'CISCO' in group_names"

    - name: Obter VLANs e interfaces - Switch HP
      ansible.netcommon.cli_command:
        command: display vlan
      when: "'HP_A3600' in group_names"
      register: hp_output
      failed_when: false

    - name: Exibir VLANs por porta - HP
      ansible.builtin.debug:
        msg: |
          {{ inventory_hostname }}:
          {% set current_vlan = '' %}
          {% for line in hp_output.stdout_lines %}
            {% if 'VLAN ID:' in line %}
              {% set current_vlan = (line | regex_search('VLAN ID: (\\d+)', '\\1')) %}
            {% elif 'Port:' in line %}
              {% set ports = (line | regex_replace('Port: ', '')).split(',') %}
              {% for port in ports %}
Porta: {{ port | trim }} - VLAN: {{ current_vlan }}
              {% endfor %}
            {% endif %}
          {% endfor %}
      when: "'HP_A3600' in group_names"
