---
- name: Coletar e Exibir Informações das Portas do Switch
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
    - name: 1. Tentar coletar fatos estruturados das interfaces
      cisco.ios.ios_facts:
        gather_subset:
          - "!all"
          - "interfaces"
      register: switch_facts

    - name: 2. Exibir status (APENAS se os fatos estruturados existirem)
      ansible.builtin.debug:
        msg: >-
          Porta: {{ item.key }} |
          Status: {{ item.value.oper_status }} |
          Descrição: {{ item.value.description | default('N/A') }}
      loop: "{{ switch_facts.ansible_facts.net_interfaces | dict2items }}"
      # Esta condição faz com que a tarefa seja PULADA se 'net_interfaces' não for encontrado
      when: switch_facts.ansible_facts.net_interfaces is defined
      loop_control:
        label: "{{ item.key }}"

    - name: 3. Executar 'show ip interface brief' (Método Confiável)
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: sh_ip_int_brief

    - name: 4. Exibir saída bruta das interfaces (Fonte de Verdade)
      ansible.builtin.debug:
        var: sh_ip_int_brief.stdout_lines
