---
- name: Coletar e Exibir Informações das Portas do Switch
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
    - name: 1. Coletar fatos das interfaces
      cisco.ios.ios_facts:
        gather_subset:
          - "!all"
          - "interfaces"
      register: switch_facts

    - name: 1.5. INSPECIONAR a variável completa (Adicione esta tarefa)
      ansible.builtin.debug:
        var: switch_facts

    - name: 2. Exibir status das interfaces coletadas
      ansible.builtin.debug:
        msg: >-
          Porta: {{ item.key }} |
          Status: {{ item.value.oper_status }} |
          Descrição: {{ item.value.description | default('N/A') }}
      # A linha abaixo está temporariamente desabilitada para o debug funcionar
      # loop: "{{ switch_facts.ansible_facts.net_interfaces | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
