---
- name: Mostrar VLANs por porta nos switches
  hosts: all
  gather_facts: no

  tasks:

    - name: Obter VLANs e interfaces - Switch Cisco
      ansible.netcommon.cli_command:
        command: show vlan brief
      when: "'CISCO' in group_names"
      register: cisco_output
      failed_when: false

    - name: Obter VLANs e interfaces - Switch HP
      ansible.netcommon.cli_command:
        command: display vlan
      when: "'HP_A3600' in group_names"
      register: hp_output
      failed_when: false
