---
- name: Coletar Informações das Portas do Switch
  hosts: all # Usaremos um grupo de inventário chamado 'switches'
  gather_facts: no # Essencial para dispositivos de rede
  connection: ansible.netcommon.network_cli # Usa a conexão apropriada para rede

  tasks:
    - name: 1. Coletar fatos das interfaces (Método Estruturado)
      cisco.ios.ios_facts:
        gather_subset:
          - interfaces
      register: switch_facts

    - name: 2. Exibir status das interfaces coletadas
      ansible.builtin.debug:
        msg: "Interface: {{ item.key }}, Status: {{ item.value.oper_status }}, Descrição: {{ item.value.description | default('N/A') }}"
      loop: "{{ switch_facts.ansible_facts.net_interfaces | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: 3. Executar 'show ip interface brief' (Método de Comando Bruto)
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: sh_ip_int_brief

    - name: 4. Exibir saída do comando 'show ip interface brief'
      ansible.builtin.debug:
        var: sh_ip_int_brief.stdout_lines
