---
- name: Mostrar VLANs com cli_command (HP Comware)
  hosts: all
  gather_facts: no
  tasks:
    - name: Executar "display vlan"
      ansible.netcommon.cli_command:
        command: display vlan
      register: resultado

    - name: Mostrar saída
      debug:
        var: resultado.stdout_lines
