---
- name: Mostrar VLANs nos switches
  hosts: all
  gather_facts: no
  tasks:

    - name: VLANs no switch Cisco
      ios_command:
        commands:
          - show vlan brief
      register: resultado_cisco
      when: "'CISCO' in group_names"

    - name: Exibir resultado do Cisco
      debug:
        var: resultado_cisco.stdout_lines
      when: "'CISCO' in group_names"

    - name: VLANs no switch HP
      raw: display vlan
      register: resultado_hp
      ignore_errors: yes
      when: "'HP' in group_names"

    - name: Exibir resultado do HP
      debug:
        var: resultado_hp.stdout_lines
      when: "'HP' in group_names"
