---
- name: Testar conectividade do AWX com a Internet
  hosts: localhost
  connection: local # Executa no próprio Execution Environment
  gather_facts: no

  tasks:
    - name: "Executa o comando ping para o DNS do Google (8.8.8.8)"
      ansible.builtin.command: "ping -c 4 8.8.8.8"
      register: ping_result
      ignore_errors: true

    - name: "SUCESSO: O AWX tem acesso à internet."
      ansible.builtin.debug:
        msg: "Acesso à internet confirmado a partir do Execution Environment."
      when: ping_result.rc == 0

    - name: "FALHA: O AWX NÃO tem acesso à internet."
      ansible.builtin.debug:
        msg: "FALHA: Não foi possível pingar a internet a partir do Execution Environment."
      when: ping_result.rc != 0---
- hosts: all
  gather_facts: false
  tasks:
    - ping:
