---
- name: Criar VLAN 114 no HP A3600 (Comware 5) usando comware_command
  hosts: all
  gather_facts: no
  #connection: network_cli
  vars:
    vlan_id: 114
    vlan_name: ansible114

  tasks:
    - name: Criar VLAN e definir nome
      h3c_open.comware.comware_command:
        type: config
        command:
          - system-view
          - vlan {{ vlan_id }}
          - name {{ vlan_name }}
          - quit
      register: resultado

    - name: Exibir resultado da criação da VLAN
      debug:
        var: resultado.response
