---
- name: CRUD de VLAN no HP A3600 via Ansible AWX usando raw
  hosts: all
  gather_facts: no
  vars:
    vlan_action: "{{ vlan_action }}"
    vlan_id: "{{ vlan_id }}"
    vlan_name: "{{ vlan_name }}"

  tasks:
    - name: VLANs no switch HP

      ansible.builtin.raw: |
        "system-view\n"
        "vlan {{ vlan_id }}\n"
        "name {{ vlan_name }}\n"
        "quit\n"
      register: resultado_hp
      ignore_errors: yes
      when: "'HP_A3600' in group_names"

    - name: Exibir resultado do HP
      debug:
        var: resultado_hp.stdout_lines
      when: "'HP_A3600' in group_names"
