---
- name: CRUD de VLAN no HP A3600 via Ansible AWX usando raw
  hosts: all
  gather_facts: no
  vars:
    vlan_action: "{{ vlan_action | default('create') }}"
    vlan_id: "{{ vlan_id | default('111') }}"
    vlan_name: "{{ vlan_name | default('VLAN10') }}"

  tasks:
    - name: Verificar se a VLAN existe no HP 3600
      ansible.builtin.raw: display vlan {{ vlan_id }}
      register: vlan_check_hp
      ignore_errors: yes
